### ISSUE TITLE
Not able to use the plugin and the Text tool

### ISSUE THREAD

**Issue by Marcosffn** [raw-bacon/vi-xournalpp#16]
Hi, I loved this plugin so much, it's very very good, but I am not being able to used it and insert text at the same time. When I click in text and start typing just doesn't works, it begins to change through all the modes, like, it's just not possible to type and use this plugin at the same time. Please, if you could solve this problem, I would be much grateful. Sorry for my bad english.

**Comment by raw-bacon** [comment]
First of all, I don't think you realise how happy it makes me that some is using this plugin, thank you so much!

 I am aware of this issue but unaware of any possible solutions. My own personal workaround is to just always use TeX mode, but I realize that this is much less convenient.

Sorry for the disappointing response, and thanks again for your nice words!

**Comment by raw-bacon** [comment]
For more background around this, see this discussion on the xournalpp repo:

https://github.com/xournalpp/xournalpp/discussions/2931

**Comment by JohnnyLAmpAz** [comment]
As a workaround I use the LaTeX math tool with `i`, because you can type text in there, and by escaping the math mode by 
surrounding my text between two `$`. Like explained in the Xournal++ documentation [here](https://xournalpp.github.io/guide/tools/latex/#basic-latex-formulas).

![image](https://user-images.githubusercontent.com/29355695/202903711-5c11b15f-cbbb-4e98-8f32-329b6068eed6.png)

As a plus you can still use LaTeX commands and add some inline math for example.

Btw I also love this plugin, made me so efficient while taking notes! Thank you very much for your work :love_you_gesture: . I even mentioned this in xournalpp/xournalpp#919 for others looking for the same thing: _EFFICIENCY_.

**Comment by raw-bacon** [comment]
@JohnnyLAmpAz Thanks for the compliments and for mentioning this over on the xournalpp repo. It looks like this increased my project's visibility quite a bit :)

One thing that has always bothered me with the TeX workaround was that the TeX tool's output was always black (which is suboptimal for my use case). However, I just realized that changing the color of the Text tool also changes the color of the TeX tool, thanks to some magic in the parsing of the TeX template files shipped with Xournal++.

In light of this, in 836e72f9ed087470cf50bd3ef71a171be213e059 I changed the behaviour of color mode to also change the color of the text tool.

Thanks to this minor hack, combined with the fact that you made me aware of the "escape with `$`" trick, I am now finally convinced that that the TeX tool is a suitable replacement for the text tool.

**Comment by JohnnyLAmpAz** [comment]
Nice change! I was aware of this but kept doing the trick the manual way selecting the text tool and then the color :man_facepalming: . 

> One thing that has always bothered me with the TeX workaround was that the TeX tool's output was always black (which is suboptimal for my use case).

You can also tweak the default TeX template to change the background color thus making white text visible in the preview. Like this:

![image](https://user-images.githubusercontent.com/29355695/202922982-a2b4da4f-d03f-444f-b183-181515fc9d40.png)

But this will also produce a non transparent background of the text created. You can match the exact bg color of your document. It would be better if Xournal++ itself would copy the bg color of the document and use it for the preview but may not be applicable when annotating PDF file.

**Comment by raw-bacon** [comment]
In version 1.2.x, this seems to be fixed thanks to the [refactor of key event handling](https://github.com/xournalpp/xournalpp/pull/4797) in the xournalpp repository. I will add the text tool keybinding, finally closing this issue :)
