### ISSUE TITLE
Wrong shortcut when upgrading from 1.1.3 to 1.2.x

### ISSUE THREAD

**Issue by Rehan-MALAK** [raw-bacon/vi-xournalpp#20]
Hi @raw-bacon, 

First of all, thanks a lot for your vi-xournalpp plugin. I wouldn't use xournalpp without it !

During the summer, Debian upgraded their xournalpp versions : 
-xournalpp (1.1.3-1)  Thu, 01 Dec 2022
-xournalpp (1.2.0-1)  Mon, 31 Jul 2023
-xournalpp (1.2.1-1) Tue, 29 Aug 2023

Unfortunately, the 1.2.x versions broke some shortcuts. 
Indeed, if I use the 'w'rite mode or the 'e'rase mode, and then type '1', '2', '3', '4', '5' to change the size, it doesn't work anymore, instead it changes the color in 'w' mode and doesn't do anything in 'e' mode.

Could we do something about this ?

Thanks !

**Comment by raw-bacon** [comment]
Hi @Rehan-MALAK,

Apparently the number key accelerators get sent directly to xournal++ and do not pass through the plugin anymore. I will push a fix very soon, adding a new mode called `resize`, which will be accessed using `F` (capital f). The thickness can then be changed using `a`, `s`, `d`, `f`, `g`. I hope this will be comfortable enough.

Thanks for letting me know!
