### ISSUE TITLE
Add shortcut for selecting the Hand tool

### ISSUE THREAD

**Issue by iCromix** [raw-bacon/vi-xournalpp#22]
Hello

I would like to suggest adding a shortcut (probably in tool mode) to select the hand tool in order to drag the page around.

Thanks for the plugin

**Comment by raw-bacon** [comment]
Thanks for the idea! I mapped it to `<Shift>f`.

**Comment by BertrandSim** [comment]
correct me if I'm wrong, but doesn't this conflict with the resize mode?

**Comment by raw-bacon** [comment]
Good point, mapped to `<Shift>d` instead.
